# ─────────────────────────────────────────────────────────────────────────────
# paths.local.example.py  —  LOCAL PATH OVERRIDES (template)
#
# HOW TO USE:
#   1. Copy this file and rename it to:  paths.local.py
#   2. Fill in the absolute paths to wherever your data files live.
#   3. paths.local.py is gitignored — it will never be committed.
#      Every contributor maintains their own copy.
#
# WHICH PATHS TO SET:
#   Only set a variable if your file lives somewhere OTHER than the default
#   location under the project root.  You can leave any line commented out
#   to keep the default relative path.
#
# DEFAULT LOCATIONS (relative to project root):
#   explainability/alert_table/alert_table_{V}/alert_table_{V}.parquet
#   processed_datasets/ueba_dataset_{V}/ueba_dataset_{V}_train.parquet
#   where {V} = MODEL_VERSION (default "6")
#
# NOTE: archived v1–v5 artifact generations live under legacy/ (gitignored).
#   Point MODEL_VERSION at an old version only after moving its artifacts back
#   out of legacy/ (the derived paths do not search legacy/).
# ─────────────────────────────────────────────────────────────────────────────

# ── Raw CERT dataset root (REQUIRED for preprocessing notebooks) ──────────────
# Set this to the folder containing the CERT r6.2 CSVs on your machine.
# There is no project-relative default — every contributor must set this.
# CERT_PATH = r"C:\Users\yourname\Documents\Datasets\CERT_r6.2"

# ── Active model version ──────────────────────────────────────────────────────
# Controls which numbered model artifacts (encoder, isolation forest, alert table,
# ueba dataset) are used by default across all notebooks, scripts, and the
# pipeline. (`python -m ueba.pipeline --version N` overrides this per-invocation.)
# MODEL_VERSION = "6"

# ── Live simulation model version ─────────────────────────────────────────────
# Defaults to MODEL_VERSION if not set.  Set this only if your deployed/live
# scoring model differs from the version used in offline training.
# LIVE_MODEL_VERSION = "6"

# ── Dashboard paths ───────────────────────────────────────────────────────────
# Absolute path to the alert table produced by `ueba.pipeline build-alerts`.
# Parquet is preferred; the dashboard falls back to CSV if only that exists.
# ANALYST_TABLE = r"C:\Users\yourname\data\alert_table_6.parquet"

# Absolute path to the UEBA training dataset produced by `ueba.pipeline preprocess`.
# UEBA_DATASET = r"C:\Users\yourname\data\ueba_dataset_6_train.parquet"

# Absolute path to the peer-group baselines parquet (department × day × feature means).
# Generated by grouping ueba_dataset_{V}_train on (department, day).  Leave commented
# to use the default location: processed_datasets/ueba_dataset_{V}/peer_baselines_{V}.parquet
# PEER_BASELINES_PATH = r"C:\Users\yourname\data\peer_baselines_6.parquet"

# ── HuggingFace repository overrides ─────────────────────────────────────────
# Override the HF org or specific repo IDs for uploads and cloud downloads.
# Useful when testing against a personal fork or staging repo.
# HF_ORG          = "InsiderGuard-AI"          # base org (default)
# HF_DATASET_REPO = "my-org/ueba-v6"           # overrides HF_ORG-derived default
# HF_MODEL_REPO   = "my-org/ueba-models-v6"    # overrides HF_ORG-derived default
