import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


class HybridRiskScatter:
    """
    Constructs and visualizes a hybrid 2D risk surface using both Autoencoder and Isolation Forest percentiles.
    This class is designed to operate on calibrated percentile scores.
    """
    
    def __init__(self, threshold_percentile: float=95.0, alpha: float=0.5, beta: float=0.5) -> None:
        """
        Initializes the Hybrid Risk Scatter.
        
        Args:
            threshold_percentile: The percentile used to define high-risk boundary
            alpha: The weight of AE percentile in hybrid score
            beta: The weight of IF percentile in hybrid score
            
        Returns:
            None:
        """
        self.threshold_percentile = threshold_percentile
        self.alpha = alpha
        self.beta = beta
        
        
    def build_dataframe(self, metadata: pd.DataFrame, ae_percentiles: np.ndarray, if_percentiles: np.ndarray) -> pd.DataFrame:
        """
        Constructs the hybrid risk DataFrame.
        
        Args:
            metadata: The metadata columns (e.g., (user, pc, day))
            ae_percentiles: The AE percentile scores
            if_percentiles: The IF percentile scores
            
        Returns:
            pd.DataFrame: A structured hybrid risk DataFrame
        """
        # Creating the DataFrame
        df = metadata.reset_index(drop=True).copy()
        df["ae_percentile"] = ae_percentiles
        df["if_percentile"] = if_percentiles
        
        # Computing the weighted hybrid risk score
        df["hybrid_score"] = ((self.alpha * df["ae_percentile"]) + (self.beta * df["if_percentile"]))
        
        # Assigning quadrant labels
        df["risk_quadrant"] = df.apply(self._assign_quadrant, axis=1)
        
        return df
    
    
    def _assign_quadrant(self, row: pd.Series) -> str:
        """
        Assigns the risk quadrant label.
        
        Args:
            row: The row of data that's being assigned a label
            
        Returns:
            str: The risk label
        """
        high_ae = row["ae_percentile"] >= self.threshold_percentile
        high_if = row["if_percentile"] >= self.threshold_percentile
        
        if high_ae and high_if:
            return "High AE / High IF"
        elif high_ae and not high_if:
            return "High AE / Low IF"
        elif not high_ae and high_if:
            return "Low AE / High IF"
        else:
            return "Low AE / Low IF"
        
        
    def plot_scatter(self, df: pd.DataFrame, save_path: str | None=None, title: str="Hybrid Risk Surface (AE vs. IF Percentiles)") -> None:
        """
        Plots a hybrid 2D risk scatter.
        
        Args:
            df: The DataFrame generated by `build_dataframe`
            title: The title to give the figure
            
        Returns:
            None:
        """
        plt.figure(figsize=(8,6))
        
        scatter = plt.scatter(
            x=df["ae_percentile"],
            y=df["if_percentile"],
            c=df["hybrid_score"],
            marker=".",
            cmap="coolwarm",
            # edgecolors="black",
            # linewidths=1,
            alpha=0.7
        )
        
        plt.axvline(self.threshold_percentile, linestyle="--", color=("k"))
        plt.axhline(self.threshold_percentile, linestyle="--", color=("k"))
        
        plt.colorbar(scatter, label="Hybrid Risk Score")
        plt.xlabel("AE Percentile")
        plt.ylabel("IF Percentile")
        plt.title(title)
        plt.grid(True)
        plt.tight_layout()
        
        # Saves the figure if a save path is specified
        if save_path:
            save_dir = r"explainability\hybrid_risk_plot"
            save_path = os.path.join(save_dir, save_path)
            plt.savefig(save_path)
            
        plt.show()