import os
import numpy as np
import pandas as pd
import tensorflow as tf


class ReconstructionErrorExplainer:
    """
    Decomposes an Autoencoder's reconstruction error into:
        - Feature-level errors
        - Percentage contribution per feature
        - Optional behavioral group-level aggregation
    """
    
    def __init__(self, feature_names: list, feature_groups: dict | None=None) -> None:
        """
        Initializes the explainer.
        
        Args:
            feature_names: An ordered list of feature names matching model input order
            feature_groups: A dictionary mapping of group names to feature names
            
        Returns:
            None:
        """
        self.feature_names = feature_names
        self.feature_groups = feature_groups
        self.feature_index_map = {name:idx for idx, name in enumerate(feature_names)}
        
        
    def compute_feature_error(self, input_data: np.ndarray, reconstructed_data: np.ndarray) -> np.ndarray:
        """
        Computes squared reconstruction error per feature.
        
        Args:
            input_data: The original input features of shape: (n_samples, n_features)
            reconstructed_data: The reconstructed features generated by autoencoders of shape: (n_samples, n_features)
            
        Returns:
            np.ndarray: The squared error per feature of shape: (n_samples, n_features)
        """
        return np.square(
            input_data.astype(np.float32, copy=False) - reconstructed_data.astype(np.float32, copy=False)
        )
    
    
    def compute_total_error(self, feature_error: np.ndarray) -> np.ndarray:
        """
        Computes the total reconstruction error per sample.
        
        Args:
            feature_error: An array containing feature-level errors
            
        Returns:
            np.ndarray: The total reconstruction error per sample
        """
        return np.sum(feature_error, axis=1)
    
    
    def compute_contribution_ratio(self, feature_error: np.ndarray, total_error: np.ndarray) -> np.ndarray:
        """
        Computes the percentage contributions fo each feature to the total error.
        
        Args:
            feature_error: An array containing feature-level errors
            total_errors: An array containing total reconstruction error per sample
            
        Returns:
            np.ndarray: The contribution ratio of the shape: (n_samples, n_features)
        """
        # Ensuring there's no division by 0
        total_error_safe = np.where(total_error == 0, 1e-8, total_error)
        
        contribution_ratio = feature_error / total_error_safe[:, np.newaxis]
        return contribution_ratio
    
    
    def _build_family_map(self, features: list) -> dict:
        """
        Groups features by their underlying behavioral concept.

        Features sharing the same base name (e.g., logon_count, logon_count_zscore,
        logon_count_rolling_delta) are placed in one family so they count as a single
        concept during group aggregation rather than inflating the group score.
        
        Args:
            features: List of feature columns
            
        Returns:
            dict: Family dictionary to use for group reconstruction error
        """
        families = {}
        for f in features:
            if f.endswith("_zscore"):
                base = f[: -len("_zscore")]
            elif f.endswith("_rolling_delta"):
                base = f[: -len("_rolling_delta")]
            else:
                base = f
            families.setdefault(base, []).append(f)
        return families


    def compute_group_error(self, feature_error: np.ndarray) -> np.ndarray | None:
        """
        Aggregates feature errors by behavioral groups.

        Returns the mean of concept-family means so that:
        - Groups with different feature counts are directly comparable (no size inflation)
        - Correlated representations (raw, zscore, rolling_delta) of the same concept
          count as one

        Args:
            feature_error: An array containing feature-level errors

        Returns:
            np.ndarray: An aggregate array of shape: (n_samples, n_groups)
        """
        if self.feature_groups is None:
            return None

        group_errors = []

        for group, features in self.feature_groups.items():
            families = self._build_family_map(features)

            family_means = []
            for family_features in families.values():
                indices = [self.feature_index_map[f] for f in family_features if f in self.feature_index_map]
                if indices:
                    family_means.append(np.mean(feature_error[:, indices], axis=1))

            if family_means:
                group_error = np.mean(np.stack(family_means, axis=1), axis=1)
            else:
                group_error = np.zeros(feature_error.shape[0])

            group_errors.append(group_error)

        return np.vstack(group_errors).T
    
    
    def explain(self, input_data: np.ndarray, model: tf.keras.Model, batch_size: int=4096) -> dict:
        """
        Generates a full reconstruction explanation.

        Args:
            input_data: The input data
            model: A trained autoencoder model
            batch_size: Batch size for model predictions

        Returns:
            dict: A dictionary containing feature error, total error, contribution ratio, and group error
        """
        input_data = np.asarray(input_data, dtype=np.float32)
        x_pred = model.predict(input_data, verbose=0, batch_size=batch_size)
        
        feature_error = self.compute_feature_error(input_data, x_pred)
        total_error = self.compute_total_error(feature_error)
        contribution_ratio = self.compute_contribution_ratio(feature_error, total_error)
        group_error = self.compute_group_error(feature_error)
        
        error_dict = {
            "feature_error": feature_error,
            "total_error": total_error,
            "contribution_ratio": contribution_ratio,
            "group_error": group_error
        }
        
        return error_dict
    
    
    def explain_to_df(
        self,
        input_data: np.ndarray,
        model: tf.keras.Model,
        metadata: pd.DataFrame | None=None,
        include_feat_err: bool=True,
        include_contributions: bool=True,
        batch_size: int=4096
    ) -> pd.DataFrame:
        """
        Generates a structured Pandas DataFrame containing reconstruction explanations.

        Args:
            input_data: The scaled input data
            model: A trained autoencoder model
            metadata: Optional metadata columns
            include_feat_err: Includes raw per-feature reconstruction errors
            include_contributions: Includes per-feature contribution ratios
            batch_size: Batch size for model predictions

        Returns:
            pd.DataFrame: A structured DataFrame containing metadata, total error, group-level errors, and optional feature-level details
        """
        results = self.explain(input_data, model, batch_size=batch_size)

        feature_error = results["feature_error"]
        total_error = results["total_error"]
        contribution_ratio = results["contribution_ratio"]
        group_error = results["group_error"]

        columns = {}

        if metadata is not None:
            meta = metadata.reset_index(drop=True)
            for col in meta.columns:
                columns[col] = meta[col].values

        columns["total_reconstruction_error"] = total_error

        if (self.feature_groups is not None) and (group_error is not None):
            for idx, group in enumerate(self.feature_groups.keys()):
                columns[f"group_error_{group}"] = group_error[:, idx]

        if include_feat_err:
            for idx, feature in enumerate(self.feature_names):
                columns[f"error_{feature}"] = feature_error[:, idx]

        if include_contributions:
            for idx, feature in enumerate(self.feature_names):
                columns[f"contribution_{feature}"] = contribution_ratio[:, idx]

        return pd.DataFrame(columns)
    

def save_table(df: pd.DataFrame, save_path: str) -> None:
    """
    Saves the DataFrame table as a Parquet file to the specified path.

    Args:
        df: DataFrame table
        save_path: Path to save table to ending in "*.parquet"

    Returns:
        None:
    """
    output_dir = r"explainability\reconstruction_error"
    os.makedirs(output_dir, exist_ok=True)

    full_path = os.path.join(output_dir, save_path)
    df.to_parquet(full_path, index=False)

    print("Successfully saved to:", full_path)